import { NextRequest } from "next/server";
import { withApiMiddleware, successResponse } from "@/lib/api-middleware";
import { z } from "zod";

const robotsGeneratorSchema = z.object({
  sitemapUrl: z.string().url().optional(),
  allowAll: z.boolean().default(true),
  disallowPaths: z.array(z.string()).default([]),
  allowPaths: z.array(z.string()).default([]),
  crawlDelay: z.number().min(0).max(60).optional(),
  userAgents: z.array(z.string()).default(["*"]),
});

interface RobotsGeneratorResult {
  content: string;
  suggestions: string[];
  processingTime: number;
}

async function handler(
  request: NextRequest,
  context: any,
  validatedData: z.infer<typeof robotsGeneratorSchema>
) {
  const startTime = Date.now();
  const {
    sitemapUrl,
    allowAll,
    disallowPaths,
    allowPaths,
    crawlDelay,
    userAgents,
  } = validatedData;

  let content = "# robots.txt generated by SEO Tools Platform\n\n";

  // Generate for each user agent
  userAgents.forEach((userAgent) => {
    content += `User-agent: ${userAgent}\n`;

    if (allowAll) {
      content += "Allow: /\n";
    }

    // Add disallow paths
    disallowPaths.forEach((path) => {
      content += `Disallow: ${path}\n`;
    });

    // Add allow paths
    allowPaths.forEach((path) => {
      content += `Allow: ${path}\n`;
    });

    // Add crawl delay if specified
    if (crawlDelay !== undefined && crawlDelay > 0) {
      content += `Crawl-delay: ${crawlDelay}\n`;
    }

    content += "\n";
  });

  // Add sitemap
  if (sitemapUrl) {
    content += `Sitemap: ${sitemapUrl}\n`;
  }

  // Generate suggestions
  const suggestions: string[] = [];

  if (!sitemapUrl) {
    suggestions.push("Sitemap URL'si eklemeniz önerilir");
  }

  if (disallowPaths.length === 0 && allowAll) {
    suggestions.push("Özel dizinleri (örn: /admin/, /api/) engellemek isteyebilirsiniz");
  }

  if (!disallowPaths.includes("/admin") && !disallowPaths.includes("/admin/")) {
    suggestions.push("Admin panelini engellemek için '/admin/' ekleyin");
  }

  if (!disallowPaths.includes("/api") && !disallowPaths.includes("/api/")) {
    suggestions.push("API endpoint'lerini engellemek için '/api/' ekleyin");
  }

  const result: RobotsGeneratorResult = {
    content,
    suggestions,
    processingTime: Date.now() - startTime,
  };

  return successResponse(result);
}

export const POST = withApiMiddleware(handler, {
  requireAuth: false,
  toolType: "tools",
  enableCache: true,
  cacheTTL: 3600,
  validationSchema: robotsGeneratorSchema,
});
